categories:
- service
conversations:
- - wait
  - Please wait a moment, the customer service robot is rushing over to support.
- - wait
  - The customer service robot is looking for the key to this room, please wait a moment.
- - wait
  - The customer service robot has forgotten the password of this room, please give him some time.

- - can you help me
  - Sure, how can I help you?
- - can you help me
  - how can I help you?
- - can you help me
  - OfCourse, how can I help you?

- - help
  - Ok, Give me your problem.
- - help
  - Give me your problem.

